import type { GlobalConfig, Block } from 'payload'
import { isSuperAdmin } from '../access/roles'
import { revalidateHomepage } from './hooks/revalidateHomepage'

const heroCarouselBlock: Block = {
  slug: 'carousel',
  labels: {
    singular: 'Hero Carousel',
    plural: 'Hero Carousels',
  },
  fields: [
    {
      name: 'carouselHeight',
      type: 'select',
      label: 'Carousel Height Format',
      defaultValue: 'medium',
      options: [
        { label: 'Short (400px)', value: 'short' },
        { label: 'Medium (550px)', value: 'medium' },
        { label: 'Tall (700px)', value: 'tall' },
        { label: 'Full Screen', value: 'fullscreen' },
      ],
      required: true,
    },
    {
      name: 'carouselLayout',
      type: 'select',
      label: 'Carousel Layout Format',
      defaultValue: 'fullWidth',
      options: [
        { label: 'Full Width', value: 'fullWidth' },
        { label: 'Boxed Container', value: 'boxed' },
      ],
      required: true,
    },
    {
      name: 'carouselImageOpacity',
      type: 'select',
      label: 'Carousel Image Opacity (Dimming)',
      defaultValue: '100',
      options: [
        { label: '100% (Normal)', value: '100' },
        { label: '90%', value: '90' },
        { label: '80%', value: '80' },
        { label: '70%', value: '70' },
        { label: '60%', value: '60' },
        { label: '50%', value: '50' },
      ],
      required: true,
    },
    {
      name: 'carouselAutoplay',
      type: 'checkbox',
      label: 'Autoplay Slides',
      defaultValue: true,
    },
    {
      name: 'carouselAutoplayInterval',
      type: 'number',
      label: 'Autoplay Speed (in milliseconds)',
      defaultValue: 5000,
      admin: {
        condition: (data, siblingData) => Boolean(siblingData?.carouselAutoplay),
      },
    },
    {
      name: 'slides',
      type: 'array',
      label: 'Hero Carousel Slides',
      maxRows: 10,
      fields: [
        {
          name: 'image',
          type: 'upload',
          relationTo: 'media',
          required: true,
          admin: {
            description: 'Slide image. WARNING: To change this image, click the "X" button to clear the field, then select or upload a new one. DO NOT click the pencil "Edit" icon to replace the file inside the media drawer, as that will overwrite the shared media asset globally across all pages!',
          },
        },
        { name: 'alt',   type: 'text' },
        { name: 'link',  type: 'text', admin: { description: 'Optional: clicking the slide goes here' } },
        {
          name: 'imageAlignment',
          type: 'select',
          label: 'Image Alignment (Positioning)',
          defaultValue: 'center',
          options: [
            { label: 'Center', value: 'center' },
            { label: 'Top', value: 'top' },
            { label: 'Bottom', value: 'bottom' },
            { label: 'Left', value: 'left' },
            { label: 'Right', value: 'right' },
          ],
        },
        {
          name: 'overlayOpacity',
          type: 'select',
          label: 'Dark Overlay Opacity',
          defaultValue: 'medium',
          options: [
            { label: '0% (None)', value: 'none' },
            { label: '20% (Light)', value: 'light' },
            { label: '40% (Medium)', value: 'medium' },
            { label: '60% (Dark)', value: 'dark' },
            { label: '80% (Extra Dark)', value: 'extraDark' },
          ],
        },
        {
          name: 'textAlignment',
          type: 'select',
          label: 'Text Alignment',
          defaultValue: 'left',
          options: [
            { label: 'Left', value: 'left' },
            { label: 'Center', value: 'center' },
            { label: 'Right', value: 'right' },
          ],
        },
        { name: 'title', type: 'text', label: 'Slide Heading Overlay' },
        { name: 'subtitle', type: 'text', label: 'Slide Subtitle / Description' },
        { name: 'buttonLabel', type: 'text', label: 'Button Label' },
        { name: 'buttonLink', type: 'text', label: 'Button Link' },
      ],
    },
  ],
}

const servicesGridBlock: Block = {
  slug: 'services',
  labels: {
    singular: 'Services Grid ("We Offer")',
    plural: 'Services Grids',
  },
  fields: [
    {
      name: 'heading',
      type: 'text',
      defaultValue: 'WE OFFER',
      required: true,
    },
    {
      name: 'align',
      type: 'select',
      label: 'We Offer Heading Alignment',
      defaultValue: 'center',
      options: [
        { label: 'Left', value: 'left' },
        { label: 'Center', value: 'center' },
        { label: 'Right', value: 'right' },
      ],
      required: true,
    },
    {
      name: 'size',
      type: 'select',
      label: 'We Offer Heading Size',
      defaultValue: 'medium',
      options: [
        { label: 'Small', value: 'small' },
        { label: 'Medium', value: 'medium' },
        { label: 'Large', value: 'large' },
      ],
      required: true,
    },
    {
      name: 'services',
      type: 'relationship',
      relationTo: 'services',
      hasMany: true,
      admin: { description: 'Select up to 4 service cards to display' },
    },
    {
      name: 'bg',
      type: 'select',
      label: 'Background Theme',
      defaultValue: 'slate',
      options: [
        { label: 'White (Standard)', value: 'white' },
        { label: 'Light Slate Gray', value: 'slate' },
        { label: 'Warm Cream', value: 'cream' },
      ],
      required: true,
    },
    {
      name: 'showUnderline',
      type: 'checkbox',
      label: 'Show Heading Underline Decoration',
      defaultValue: true,
      required: true,
    },
  ],
}

const newsSectionBlock: Block = {
  slug: 'news',
  labels: {
    singular: 'News & Notifications Section',
    plural: 'News Sections',
  },
  fields: [
    {
      name: 'heading',
      type: 'text',
      defaultValue: 'NEWS & NOTIFICATIONS',
      required: true,
    },
    {
      name: 'align',
      type: 'select',
      label: 'News Heading Alignment',
      defaultValue: 'center',
      options: [
        { label: 'Left', value: 'left' },
        { label: 'Center', value: 'center' },
        { label: 'Right', value: 'right' },
      ],
      required: true,
    },
    {
      name: 'size',
      type: 'select',
      label: 'News Heading Size',
      defaultValue: 'medium',
      options: [
        { label: 'Small', value: 'small' },
        { label: 'Medium', value: 'medium' },
        { label: 'Large', value: 'large' },
      ],
      required: true,
    },
    {
      name: 'newsSubheading',
      type: 'text',
      defaultValue: 'Stay updated with the latest news, announcements, and achievements from MOSAI.',
    },
    {
      name: 'limit',
      type: 'number',
      label: 'Display Count',
      defaultValue: 8,
      required: true,
    },
    {
      name: 'newsViewAllLink',
      type: 'text',
      defaultValue: '/news',
      required: true,
    },
    {
      name: 'newsViewAllLabel',
      type: 'text',
      label: 'View All Button Label',
      defaultValue: 'View All Notifications',
      required: true,
    },
    {
      name: 'bg',
      type: 'select',
      label: 'Background Theme',
      defaultValue: 'white',
      options: [
        { label: 'White (Standard)', value: 'white' },
        { label: 'Light Slate Gray', value: 'slate' },
        { label: 'Warm Cream', value: 'cream' },
      ],
      required: true,
    },
    {
      name: 'showUnderline',
      type: 'checkbox',
      label: 'Show Heading Underline Decoration',
      defaultValue: true,
      required: true,
    },
  ],
}

const gallerySectionBlock: Block = {
  slug: 'gallery',
  labels: {
    singular: 'Gallery Section',
    plural: 'Gallery Sections',
  },
  fields: [
    {
      name: 'heading',
      type: 'text',
      defaultValue: 'MOSAI Gallery',
      required: true,
    },
    {
      name: 'align',
      type: 'select',
      label: 'Gallery Heading Alignment',
      defaultValue: 'center',
      options: [
        { label: 'Left', value: 'left' },
        { label: 'Center', value: 'center' },
        { label: 'Right', value: 'right' },
      ],
      required: true,
    },
    {
      name: 'size',
      type: 'select',
      label: 'Gallery Heading Size',
      defaultValue: 'medium',
      options: [
        { label: 'Small', value: 'small' },
        { label: 'Medium', value: 'medium' },
        { label: 'Large', value: 'large' },
      ],
      required: true,
    },
    {
      name: 'limit',
      type: 'number',
      label: 'Display Count',
      defaultValue: 4,
      required: true,
    },
    {
      name: 'galleryViewAllLabel',
      type: 'text',
      label: 'View All Button Label',
      defaultValue: 'View More',
      required: true,
    },
    {
      name: 'bg',
      type: 'select',
      label: 'Background Theme',
      defaultValue: 'slate',
      options: [
        { label: 'White (Standard)', value: 'white' },
        { label: 'Light Slate Gray', value: 'slate' },
        { label: 'Warm Cream', value: 'cream' },
      ],
      required: true,
    },
    {
      name: 'showUnderline',
      type: 'checkbox',
      label: 'Show Heading Underline Decoration',
      defaultValue: true,
      required: true,
    },
  ],
}

const pastEventsSectionBlock: Block = {
  slug: 'events',
  labels: {
    singular: 'Past Events Section',
    plural: 'Past Events Sections',
  },
  fields: [
    {
      name: 'heading',
      type: 'text',
      defaultValue: 'Our Past Events',
      required: true,
    },
    {
      name: 'align',
      type: 'select',
      label: 'Events Heading Alignment',
      defaultValue: 'center',
      options: [
        { label: 'Left', value: 'left' },
        { label: 'Center', value: 'center' },
        { label: 'Right', value: 'right' },
      ],
      required: true,
    },
    {
      name: 'size',
      type: 'select',
      label: 'Events Heading Size',
      defaultValue: 'medium',
      options: [
        { label: 'Small', value: 'small' },
        { label: 'Medium', value: 'medium' },
        { label: 'Large', value: 'large' },
      ],
      required: true,
    },
    {
      name: 'limit',
      type: 'number',
      label: 'Display Count',
      defaultValue: 2,
      required: true,
    },
    {
      name: 'bg',
      type: 'select',
      label: 'Background Theme',
      defaultValue: 'white',
      options: [
        { label: 'White (Standard)', value: 'white' },
        { label: 'Light Slate Gray', value: 'slate' },
        { label: 'Warm Cream', value: 'cream' },
      ],
      required: true,
    },
    {
      name: 'showUnderline',
      type: 'checkbox',
      label: 'Show Heading Underline Decoration',
      defaultValue: true,
      required: true,
    },
  ],
}

export const Homepage: GlobalConfig = {
  slug: 'homepage',
  access: {
    read: () => true,
    update: isSuperAdmin,
  },
  admin: { group: 'Site Settings' },
  fields: [
    {
      name: 'layout',
      type: 'blocks',
      label: 'Homepage Builder Sections (Reorder / Hide)',
      blocks: [
        heroCarouselBlock,
        servicesGridBlock,
        newsSectionBlock,
        gallerySectionBlock,
        pastEventsSectionBlock,
      ],
      admin: {
        description: 'Configure and reorder sections on the homepage. If left empty, all default sections will render in the standard sequence.',
      },
    },
    {
      name: 'carouselHeight',
      type: 'select',
      label: 'Default Carousel Height Format',
      defaultValue: 'medium',
      options: [
        { label: 'Short (400px)', value: 'short' },
        { label: 'Medium (550px)', value: 'medium' },
        { label: 'Tall (700px)', value: 'tall' },
        { label: 'Full Screen', value: 'fullscreen' },
      ],
      required: true,
    },
    {
      name: 'carouselLayout',
      type: 'select',
      label: 'Default Carousel Layout Format',
      defaultValue: 'fullWidth',
      options: [
        { label: 'Full Width', value: 'fullWidth' },
        { label: 'Boxed Container', value: 'boxed' },
      ],
      required: true,
    },
    {
      name: 'carouselImageOpacity',
      type: 'select',
      label: 'Default Carousel Image Opacity (Dimming)',
      defaultValue: '100',
      options: [
        { label: '100% (Normal)', value: '100' },
        { label: '90%', value: '90' },
        { label: '80%', value: '80' },
        { label: '70%', value: '70' },
        { label: '60%', value: '60' },
        { label: '50%', value: '50' },
      ],
      required: true,
    },
    {
      name: 'carouselAutoplay',
      type: 'checkbox',
      label: 'Default Autoplay Slides',
      defaultValue: true,
    },
    {
      name: 'carouselAutoplayInterval',
      type: 'number',
      label: 'Default Autoplay Speed (in milliseconds)',
      defaultValue: 5000,
      admin: {
        condition: (data) => Boolean(data?.carouselAutoplay),
      },
    },
    {
      name: 'carousel',
      type: 'array',
      label: 'Default Hero Carousel Slides',
      maxRows: 10,
      fields: [
        {
          name: 'image',
          type: 'upload',
          relationTo: 'media',
          required: true,
          admin: {
            description: 'Slide image. WARNING: To change this image, click the "X" button to clear the field, then select or upload a new one. DO NOT click the pencil "Edit" icon to replace the file inside the media drawer, as that will overwrite the shared media asset globally across all pages!',
          },
        },
        { name: 'alt',   type: 'text' },
        { name: 'link',  type: 'text', admin: { description: 'Optional: clicking the slide goes here' } },
        {
          name: 'imageAlignment',
          type: 'select',
          label: 'Image Alignment (Positioning)',
          defaultValue: 'center',
          options: [
            { label: 'Center', value: 'center' },
            { label: 'Top', value: 'top' },
            { label: 'Bottom', value: 'bottom' },
            { label: 'Left', value: 'left' },
            { label: 'Right', value: 'right' },
          ],
        },
        {
          name: 'overlayOpacity',
          type: 'select',
          label: 'Dark Overlay Opacity',
          defaultValue: 'medium',
          options: [
            { label: '0% (None)', value: 'none' },
            { label: '20% (Light)', value: 'light' },
            { label: '40% (Medium)', value: 'medium' },
            { label: '60% (Dark)', value: 'dark' },
            { label: '80% (Extra Dark)', value: 'extraDark' },
          ],
        },
        {
          name: 'textAlignment',
          type: 'select',
          label: 'Text Alignment',
          defaultValue: 'left',
          options: [
            { label: 'Left', value: 'left' },
            { label: 'Center', value: 'center' },
            { label: 'Right', value: 'right' },
          ],
        },
        { name: 'title', type: 'text', label: 'Slide Heading Overlay' },
        { name: 'subtitle', type: 'text', label: 'Slide Subtitle / Description' },
        { name: 'buttonLabel', type: 'text', label: 'Button Label' },
        { name: 'buttonLink', type: 'text', label: 'Button Link' },
      ],
    },
    {
      name: 'offersHeading',
      type: 'text',
      defaultValue: 'WE OFFER',
      required: true,
    },
    {
      name: 'offersHeadingAlignment',
      type: 'select',
      label: 'Default We Offer Heading Alignment',
      defaultValue: 'center',
      options: [
        { label: 'Left', value: 'left' },
        { label: 'Center', value: 'center' },
        { label: 'Right', value: 'right' },
      ],
      required: true,
    },
    {
      name: 'offersHeadingSize',
      type: 'select',
      label: 'Default We Offer Heading Size',
      defaultValue: 'medium',
      options: [
        { label: 'Small', value: 'small' },
        { label: 'Medium', value: 'medium' },
        { label: 'Large', value: 'large' },
      ],
      required: true,
    },
    {
      name: 'services',
      type: 'relationship',
      relationTo: 'services',
      hasMany: true,
      admin: { description: 'Select up to 4 service cards to display' },
    },
    {
      name: 'newsHeading',
      type: 'text',
      defaultValue: 'NEWS & NOTIFICATIONS',
      required: true,
    },
    {
      name: 'newsHeadingAlignment',
      type: 'select',
      label: 'Default News Heading Alignment',
      defaultValue: 'center',
      options: [
        { label: 'Left', value: 'left' },
        { label: 'Center', value: 'center' },
        { label: 'Right', value: 'right' },
      ],
      required: true,
    },
    {
      name: 'newsHeadingSize',
      type: 'select',
      label: 'Default News Heading Size',
      defaultValue: 'medium',
      options: [
        { label: 'Small', value: 'small' },
        { label: 'Medium', value: 'medium' },
        { label: 'Large', value: 'large' },
      ],
      required: true,
    },
    {
      name: 'newsSubheading',
      type: 'text',
      defaultValue: 'Stay updated with the latest news, announcements, and achievements from MOSAI.',
    },
    {
      name: 'newsDisplayCount',
      type: 'number',
      defaultValue: 8,
      admin: { description: 'How many notification items to show on the homepage' },
      required: true,
    },
    {
      name: 'newsViewAllLink',
      type: 'text',
      defaultValue: '/news',
      required: true,
    },
    {
      name: 'galleryHeading',
      type: 'text',
      defaultValue: 'MOSAI Gallery',
      required: true,
    },
    {
      name: 'galleryHeadingAlignment',
      type: 'select',
      label: 'Default Gallery Heading Alignment',
      defaultValue: 'center',
      options: [
        { label: 'Left', value: 'left' },
        { label: 'Center', value: 'center' },
        { label: 'Right', value: 'right' },
      ],
      required: true,
    },
    {
      name: 'galleryHeadingSize',
      type: 'select',
      label: 'Default Gallery Heading Size',
      defaultValue: 'medium',
      options: [
        { label: 'Small', value: 'small' },
        { label: 'Medium', value: 'medium' },
        { label: 'Large', value: 'large' },
      ],
      required: true,
    },
    {
      name: 'galleryDisplayCount',
      type: 'number',
      defaultValue: 4,
      required: true,
    },
    {
      name: 'eventsHeading',
      type: 'text',
      defaultValue: 'Our Past Events',
      required: true,
    },
    {
      name: 'eventsHeadingAlignment',
      type: 'select',
      label: 'Default Events Heading Alignment',
      defaultValue: 'center',
      options: [
        { label: 'Left', value: 'left' },
        { label: 'Center', value: 'center' },
        { label: 'Right', value: 'right' },
      ],
      required: true,
    },
    {
      name: 'eventsHeadingSize',
      type: 'select',
      label: 'Default Events Heading Size',
      defaultValue: 'medium',
      options: [
        { label: 'Small', value: 'small' },
        { label: 'Medium', value: 'medium' },
        { label: 'Large', value: 'large' },
      ],
      required: true,
    },
    {
      name: 'eventsDisplayCount',
      type: 'number',
      defaultValue: 2,
      required: true,
    },
  ],
  hooks: {
    afterChange: [revalidateHomepage],
  },
}
