import type { Block } from 'payload'

export const FlexibleRowBlock: Block = {
  slug: 'flexibleRow',
  interfaceName: 'FlexibleRowBlock',
  fields: [
    {
      name: 'containerWidth',
      type: 'select',
      label: 'Row Container Width',
      options: [
        { label: 'Boxed (Constrained)', value: 'boxed' },
        { label: 'Full Width (Viewport)', value: 'fullWidth' },
      ],
      defaultValue: 'boxed',
      required: true,
    },
    {
      name: 'rowBackground',
      type: 'select',
      label: 'Row Background Color',
      options: [
        { label: 'Transparent', value: 'transparent' },
        { label: 'Slate Light (slate-50)', value: 'slate50' },
        { label: 'Brand Navy (1A2B4A)', value: 'brandNavy' },
        { label: 'Brand Red (Japanese Red)', value: 'brandRed' },
        { label: 'Light Cream', value: 'brandCream' },
      ],
      defaultValue: 'transparent',
      required: true,
    },
    {
      name: 'rowPadding',
      type: 'select',
      label: 'Row Padding',
      options: [
        { label: 'None', value: 'none' },
        { label: 'Small', value: 'small' },
        { label: 'Medium', value: 'medium' },
        { label: 'Large', value: 'large' },
      ],
      defaultValue: 'none',
      required: true,
    },
    {
      name: 'gridGap',
      type: 'select',
      label: 'Gap between Columns',
      options: [
        { label: 'Small', value: 'small' },
        { label: 'Medium', value: 'medium' },
        { label: 'Large', value: 'large' },
      ],
      defaultValue: 'medium',
      required: true,
    },
    {
      name: 'alignItems',
      type: 'select',
      label: 'Vertical Alignment',
      options: [
        { label: 'Top', value: 'start' },
        { label: 'Center', value: 'center' },
        { label: 'Bottom', value: 'end' },
        { label: 'Stretch', value: 'stretch' },
      ],
      defaultValue: 'stretch',
      required: true,
    },
    {
      name: 'columns',
      type: 'array',
      label: 'Columns',
      minRows: 1,
      maxRows: 4,
      required: true,
      labels: {
        singular: 'Column',
        plural: 'Columns',
      },
      fields: [
        {
          name: 'width',
          type: 'select',
          label: 'Column Width (Desktop)',
          options: [
            { label: 'Full Width (12/12)', value: 'col-span-12' },
            { label: 'Half Width (6/12)', value: 'col-span-6' },
            { label: 'One Third (4/12)', value: 'col-span-4' },
            { label: 'Two Thirds (8/12)', value: 'col-span-8' },
            { label: 'One Quarter (3/12)', value: 'col-span-3' },
            { label: 'Three Quarters (9/12)', value: 'col-span-9' },
          ],
          defaultValue: 'col-span-6',
          required: true,
        },
        {
          name: 'columnStyle',
          type: 'select',
          label: 'Column Layout Style',
          options: [
            { label: 'Simple Text/Image', value: 'simple' },
            { label: 'Card Box (Shadow & Hover)', value: 'card' },
            { label: 'Bordered/Minimal Card', value: 'bordered' },
            { label: 'Glassmorphism Card', value: 'glassmorphism' },
          ],
          defaultValue: 'simple',
          required: true,
        },
        {
          name: 'backgroundColor',
          type: 'select',
          label: 'Background Color (within Column)',
          options: [
            { label: 'Transparent', value: 'transparent' },
            { label: 'Slate Light (slate-50)', value: 'slate50' },
            { label: 'Brand Navy (1A2B4A)', value: 'brandNavy' },
            { label: 'Brand Red (Japanese Red)', value: 'brandRed' },
            { label: 'Light Cream', value: 'brandCream' },
          ],
          defaultValue: 'transparent',
          required: true,
        },
        {
          name: 'textColor',
          type: 'select',
          label: 'Text Color Scheme',
          options: [
            { label: 'Default / Dark Text', value: 'dark' },
            { label: 'Light / White Text', value: 'light' },
          ],
          defaultValue: 'dark',
          required: true,
        },
        {
          name: 'columnPadding',
          type: 'select',
          label: 'Column Padding',
          options: [
            { label: 'None', value: 'none' },
            { label: 'Small', value: 'small' },
            { label: 'Medium', value: 'medium' },
            { label: 'Large', value: 'large' },
          ],
          defaultValue: 'none',
          required: true,
        },
        {
          name: 'alignment',
          type: 'select',
          label: 'Content Alignment',
          options: [
            { label: 'Left', value: 'left' },
            { label: 'Center', value: 'center' },
            { label: 'Right', value: 'right' },
          ],
          defaultValue: 'left',
          required: true,
        },
        {
          name: 'image',
          type: 'upload',
          relationTo: 'media',
          label: 'Column Image (Optional)',
          admin: {
            description: 'Image for this column. WARNING: To change this image, click the "X" button to clear the field, then select or upload a new one. DO NOT click the pencil "Edit" icon to replace the file inside the media drawer, as that will overwrite the shared media asset globally across all pages!',
          },
        },
        {
          name: 'imagePosition',
          type: 'select',
          label: 'Image Position',
          options: [
            { label: 'Top of column', value: 'top' },
            { label: 'Bottom of column', value: 'bottom' },
          ],
          defaultValue: 'top',
        },
        {
          name: 'imageShape',
          type: 'select',
          label: 'Image Shape style',
          options: [
            { label: 'Rounded Rect', value: 'rounded' },
            { label: 'Circle', value: 'circle' },
            { label: 'Square/Cover', value: 'square' },
            { label: 'Original Ratio', value: 'original' },
          ],
          defaultValue: 'rounded',
          required: true,
        },
        {
          name: 'title',
          type: 'text',
          label: 'Column Title (Optional)',
        },
        {
          name: 'content',
          type: 'richText',
          label: 'Column Content (Optional)',
        },
        {
          name: 'ctaLabel',
          type: 'text',
          label: 'Call to Action Label (Optional)',
        },
        {
          name: 'ctaLink',
          type: 'text',
          label: 'Call to Action Link (Optional)',
        },
      ],
    },
  ],
}
