/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    media: Media;
    users: User;
    news: News;
    gallery: Gallery;
    events: Event;
    services: Service;
    committee: Committee;
    jobApplications: JobApplication;
    members: Member;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    committee: CommitteeSelect<false> | CommitteeSelect<true>;
    jobApplications: JobApplicationsSelect<false> | JobApplicationsSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    homepage: Homepage;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  layoutStyle: 'sidebar' | 'rightSidebar' | 'centered' | 'fullWidth';
  heroStyle: 'none' | 'small' | 'medium' | 'large';
  /**
   * Banner image shown at the top of inner pages. WARNING: To change this image, click the "X" button to clear the field, then select or upload a new one. DO NOT click the pencil "Edit" icon to replace the file inside the media drawer, as that will overwrite the shared media asset globally across all pages!
   */
  hero?: (number | null) | Media;
  layout: (
    | RichTextBlock
    | ImageWithTextBlock
    | InfoCardBlock
    | TableBlock
    | EmbedBlock
    | CallToActionBlock
    | {
        heading: string;
        subheading?: string | null;
        image?: (number | null) | Media;
        buttons?:
          | {
              label: string;
              url: string;
              style?: ('primary' | 'secondary') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        heading?: string | null;
        stats?:
          | {
              value: string;
              label: string;
              suffix?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'statsImpact';
      }
    | {
        items?:
          | {
              text?: string | null;
              logo?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        /**
         * Animation duration in seconds — lower = faster
         */
        speed?: number | null;
        direction?: ('left' | 'right') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'marquee';
      }
    | {
        heading?: string | null;
        subheading?: string | null;
        cards?:
          | {
              image?: (number | null) | Media;
              title: string;
              description?: string | null;
              link?: string | null;
              linkLabel?: string | null;
              id?: string | null;
            }[]
          | null;
        columns?: ('2' | '3' | '4') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'showcaseCards';
      }
    | {
        heading?: string | null;
        displayStyle?: ('grid' | 'carousel') | null;
        testimonials?:
          | {
              quote: string;
              name: string;
              role?: string | null;
              avatar?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'testimonials';
      }
    | {
        heading?: string | null;
        items?:
          | {
              question: string;
              answer: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
    | {
        heading?: string | null;
        images?:
          | {
              image: number | Media;
              caption?: string | null;
              id?: string | null;
            }[]
          | null;
        layout?: ('grid' | 'masonry') | null;
        columns?: ('2' | '3' | '4') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'imageGallery';
      }
    | HelpSupportBlock
    | {
        heading?: string | null;
        subheading?: string | null;
        features?:
          | {
              icon?: (number | null) | Media;
              title: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        columns?: ('2' | '3' | '4') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'featureCards';
      }
    | {
        heading?: string | null;
        description?: string | null;
        fields?:
          | {
              label: string;
              /**
               * Unique key used in submitted data, e.g. "email"
               */
              name: string;
              type?: ('text' | 'email' | 'tel' | 'textarea' | 'number' | 'select' | 'checkbox') | null;
              placeholder?: string | null;
              required?: boolean | null;
              width?: ('full' | 'half') | null;
              options?:
                | {
                    label: string;
                    value: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        submitLabel?: string | null;
        /**
         * API route this form posts to, e.g. /api/contact
         */
        submitEndpoint: string;
        successMessage?: string | null;
        errorMessage?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'formBlock';
      }
    | {
        heading?: string | null;
        description?: string | null;
        metrics?:
          | {
              label: string;
              value: string;
              /**
               * e.g. "+12%" or "-3 states"
               */
              change?: string | null;
              trend?: ('up' | 'down' | 'neutral') | null;
              icon?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        /**
         * Shown as "Data as of ..."
         */
        lastUpdated?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'dataSnapshot';
      }
    | {
        heading?: string | null;
        description?: string | null;
        postings?:
          | {
              title: string;
              /**
               * e.g. Engineering, Research, Operations
               */
              department?: string | null;
              /**
               * e.g. Delhi, Remote, Hybrid
               */
              location?: string | null;
              type?: ('fullTime' | 'partTime' | 'internship' | 'contract') | null;
              description?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              /**
               * External application URL, or leave blank to use the form below
               */
              applyLink?: string | null;
              postedDate?: string | null;
              id?: string | null;
            }[]
          | null;
        emptyStateMessage?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'careerPosting';
      }
    | FlexibleRowBlock
    | FeaturedCardsBlock
    | {
        text: string;
        variant?:
          | (
              | 'new'
              | 'trending'
              | 'featured'
              | 'popular'
              | 'hot'
              | 'recommended'
              | 'limited'
              | 'coming-soon'
              | 'opportunity'
              | 'event'
              | 'announcement'
            )
          | null;
        size?: ('sm' | 'md' | 'lg') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'statusBadge';
      }
  )[];
  seo?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  showInNav?: boolean | null;
  navOrder?: number | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Page;
  breadcrumbs?:
    | {
        doc?: (number | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Required for accessibility — describe the image for screen readers/SEO
   */
  alt: string;
  caption?: string | null;
  /**
   * Photo credit/source, e.g. "Embassy of Japan" (optional, useful for event/official photos)
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    gallery?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageWithTextBlock".
 */
export interface ImageWithTextBlock {
  /**
   * Image for this block. WARNING: To change this image, click the "X" button to clear the field, then select or upload a new one. DO NOT click the pencil "Edit" icon to replace the file inside the media drawer, as that will overwrite the shared media asset globally across all pages!
   */
  image: number | Media;
  imagePosition: 'left' | 'right';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageWithText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InfoCardBlock".
 */
export interface InfoCardBlock {
  title?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  style: 'default' | 'highlight' | 'warning';
  id?: string | null;
  blockName?: string | null;
  blockType: 'infoCard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TableBlock".
 */
export interface TableBlock {
  caption?: string | null;
  rows?:
    | {
        isHeader?: boolean | null;
        cells?:
          | {
              value?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'table';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmbedBlock".
 */
export interface EmbedBlock {
  /**
   * YouTube embed URL or Google Form embed URL
   */
  url: string;
  height: number;
  title?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'embed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  heading?: string | null;
  body?: string | null;
  buttonText?: string | null;
  buttonLink?: string | null;
  buttonStyle: 'primary' | 'secondary' | 'outline';
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HelpSupportBlock".
 */
export interface HelpSupportBlock {
  sectionTitle?: string | null;
  sectionSubtitle?: string | null;
  layout: 'sideBySide' | 'stacked';
  supportCards?:
    | {
        title: string;
        description?: string | null;
        /**
         * Example: LifeBuoy, Headphones, BookOpen, GraduationCap
         */
        icon?: string | null;
        iconColor?: string | null;
        buttonLabel?: string | null;
        buttonUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  video?: {
    enabled?: boolean | null;
    title?: string | null;
    videoUrl?: string | null;
    /**
     * WARNING: To replace this image, clear the field first and then upload/select a new image. Do not edit the media asset directly.
     */
    poster?: (number | null) | Media;
    /**
     * Upload MP4/WebM video directly.
     */
    uploadedVideo?: (number | null) | Media;
  };
  backgroundColor?: string | null;
  cardBgColor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'helpSupport';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FlexibleRowBlock".
 */
export interface FlexibleRowBlock {
  containerWidth: 'boxed' | 'fullWidth';
  rowBackground: 'transparent' | 'slate50' | 'brandNavy' | 'brandRed' | 'brandCream';
  rowPadding: 'none' | 'small' | 'medium' | 'large';
  gridGap: 'small' | 'medium' | 'large';
  alignItems: 'start' | 'center' | 'end' | 'stretch';
  columns: {
    width: 'col-span-12' | 'col-span-6' | 'col-span-4' | 'col-span-8' | 'col-span-3' | 'col-span-9';
    columnStyle: 'simple' | 'card' | 'bordered' | 'glassmorphism';
    backgroundColor: 'transparent' | 'slate50' | 'brandNavy' | 'brandRed' | 'brandCream';
    textColor: 'dark' | 'light';
    columnPadding: 'none' | 'small' | 'medium' | 'large';
    alignment: 'left' | 'center' | 'right';
    /**
     * Legacy Image for this column. Kept for backward compatibility.
     */
    image?: (number | null) | Media;
    imagePosition?: ('top' | 'bottom') | null;
    imageShape: 'rounded' | 'circle' | 'square' | 'original';
    title?: string | null;
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    ctaLabel?: string | null;
    ctaLink?: string | null;
    /**
     * Add multiple elements of different styles (Rich Text, Cards, Images, Buttons, Videos) inside this column. If blocks are added here, they will display instead of the legacy content fields above.
     */
    blocks?:
      | (
          | {
              content: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
              blockName?: string | null;
              blockType: 'colRichText';
            }
          | {
              image?: (number | null) | Media;
              title?: string | null;
              description?: string | null;
              ctaLabel?: string | null;
              ctaLink?: string | null;
              cardStyle?: ('standard' | 'slate' | 'border') | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'colCard';
            }
          | {
              image: number | Media;
              caption?: string | null;
              aspectRatio?: ('original' | 'square' | 'video' | 'circle') | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'colImage';
            }
          | {
              label: string;
              link: string;
              style?: ('primary' | 'secondary' | 'outline') | null;
              id?: string | null;
              blockName?: string | null;
              blockType: 'colCta';
            }
          | {
              /**
               * Provide the full share link of the video (e.g. https://www.youtube.com/watch?v=...)
               */
              videoUrl: string;
              id?: string | null;
              blockName?: string | null;
              blockType: 'colEmbed';
            }
        )[]
      | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'flexibleRow';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedCardsBlock".
 */
export interface FeaturedCardsBlock {
  heading?: string | null;
  subheading?: string | null;
  columns: '2' | '3' | '4';
  cardStyle: 'standard' | 'glassmorphism' | 'navy' | 'red' | 'bordered';
  cards: {
    title: string;
    description: string;
    icon?: ('none' | 'academic' | 'globe' | 'calendar' | 'award' | 'book' | 'group' | 'info' | 'star') | null;
    /**
     * Image for this card. WARNING: To change this image, click the "X" button to clear the field, then select or upload a new one. DO NOT click the pencil "Edit" icon to replace the file inside the media drawer, as that will overwrite the shared media asset globally across all pages!
     */
    image?: (number | null) | Media;
    tag?: string | null;
    linkLabel?: string | null;
    link?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'superAdmin' | 'schoolAdmin' | 'editor' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  tag: 'ANNOUNCEMENT' | 'EVENT' | 'OPPORTUNITY' | 'RESULT' | 'NOTICE';
  /**
   * Short description shown in the notification list
   */
  excerpt: string;
  slug: string;
  /**
   * Full content (shown on the detail page)
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * If set, clicking the card redirects here instead of an internal page
   */
  externalLink?: string | null;
  publishedAt: string;
  /**
   * Pin to top of list
   */
  featured?: boolean | null;
  status?: ('published' | 'draft' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  title: string;
  image: number | Media;
  /**
   * Optional caption shown under the image (e.g. "Dr. Ashok Jain, President MOSAI")
   */
  caption?: string | null;
  /**
   * Link this image to a specific event, if applicable
   */
  event?: (number | null) | Event;
  /**
   * Group images by album/event name (optional, use only if not linking via event above)
   */
  album?: string | null;
  date?: string | null;
  /**
   * Show in homepage gallery carousel
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Paste the full YouTube embed URL (https://www.youtube.com/embed/VIDEO_ID)
   */
  youtubeUrl: string;
  eventDate?: string | null;
  organizer?: string | null;
  description?: string | null;
  /**
   * Show on homepage Past Events section
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  excerpt: string;
  image: number | Media;
  /**
   * Internal slug or external URL for the "Read More" button
   */
  link: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committee".
 */
export interface Committee {
  id: number;
  name: string;
  /**
   * e.g. President, Secretary General, Treasurer
   */
  role: string;
  /**
   * Professional designation / institution
   */
  designation?: string | null;
  photo?: (number | null) | Media;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  type: 'committee' | 'advisory' | 'faculty';
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobApplications".
 */
export interface JobApplication {
  id: number;
  name: string;
  email: string;
  resume: number | Media;
  status: 'pending' | 'reviewed' | 'accepted' | 'rejected' | 'deleted';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  name: string;
  /**
   * e.g. MOSAI-2024-0123
   */
  membershipId: string;
  photo?: (number | null) | Media;
  /**
   * e.g. Professor, Researcher, Alumni
   */
  designation?: string | null;
  /**
   * Japanese university attended on Monbukagakusho Scholarship
   */
  university?: string | null;
  joinDate?: string | null;
  email?: string | null;
  phone?: string | null;
  /**
   * Show this member in the public Members Directory
   */
  isPublic?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'news';
          value: number | News;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'pages';
        value: number | Page;
      }
    | {
        relationTo: 'news';
        value: number | News;
      };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'committee';
        value: number | Committee;
      } | null)
    | ({
        relationTo: 'jobApplications';
        value: number | JobApplication;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layoutStyle?: T;
  heroStyle?: T;
  hero?: T;
  layout?:
    | T
    | {
        richText?: T | RichTextBlockSelect<T>;
        imageWithText?: T | ImageWithTextBlockSelect<T>;
        infoCard?: T | InfoCardBlockSelect<T>;
        table?: T | TableBlockSelect<T>;
        embed?: T | EmbedBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              image?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    url?: T;
                    style?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statsImpact?:
          | T
          | {
              heading?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    suffix?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        marquee?:
          | T
          | {
              items?:
                | T
                | {
                    text?: T;
                    logo?: T;
                    id?: T;
                  };
              speed?: T;
              direction?: T;
              id?: T;
              blockName?: T;
            };
        showcaseCards?:
          | T
          | {
              heading?: T;
              subheading?: T;
              cards?:
                | T
                | {
                    image?: T;
                    title?: T;
                    description?: T;
                    link?: T;
                    linkLabel?: T;
                    id?: T;
                  };
              columns?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              displayStyle?: T;
              testimonials?:
                | T
                | {
                    quote?: T;
                    name?: T;
                    role?: T;
                    avatar?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        imageGallery?:
          | T
          | {
              heading?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              layout?: T;
              columns?: T;
              id?: T;
              blockName?: T;
            };
        helpSupport?: T | HelpSupportBlockSelect<T>;
        featureCards?:
          | T
          | {
              heading?: T;
              subheading?: T;
              features?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              columns?: T;
              id?: T;
              blockName?: T;
            };
        formBlock?:
          | T
          | {
              heading?: T;
              description?: T;
              fields?:
                | T
                | {
                    label?: T;
                    name?: T;
                    type?: T;
                    placeholder?: T;
                    required?: T;
                    width?: T;
                    options?:
                      | T
                      | {
                          label?: T;
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              submitLabel?: T;
              submitEndpoint?: T;
              successMessage?: T;
              errorMessage?: T;
              id?: T;
              blockName?: T;
            };
        dataSnapshot?:
          | T
          | {
              heading?: T;
              description?: T;
              metrics?:
                | T
                | {
                    label?: T;
                    value?: T;
                    change?: T;
                    trend?: T;
                    icon?: T;
                    id?: T;
                  };
              lastUpdated?: T;
              id?: T;
              blockName?: T;
            };
        careerPosting?:
          | T
          | {
              heading?: T;
              description?: T;
              postings?:
                | T
                | {
                    title?: T;
                    department?: T;
                    location?: T;
                    type?: T;
                    description?: T;
                    applyLink?: T;
                    postedDate?: T;
                    id?: T;
                  };
              emptyStateMessage?: T;
              id?: T;
              blockName?: T;
            };
        flexibleRow?: T | FlexibleRowBlockSelect<T>;
        featuredCards?: T | FeaturedCardsBlockSelect<T>;
        statusBadge?:
          | T
          | {
              text?: T;
              variant?: T;
              size?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  showInNav?: T;
  navOrder?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageWithTextBlock_select".
 */
export interface ImageWithTextBlockSelect<T extends boolean = true> {
  image?: T;
  imagePosition?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InfoCardBlock_select".
 */
export interface InfoCardBlockSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TableBlock_select".
 */
export interface TableBlockSelect<T extends boolean = true> {
  caption?: T;
  rows?:
    | T
    | {
        isHeader?: T;
        cells?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmbedBlock_select".
 */
export interface EmbedBlockSelect<T extends boolean = true> {
  url?: T;
  height?: T;
  title?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  buttonText?: T;
  buttonLink?: T;
  buttonStyle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HelpSupportBlock_select".
 */
export interface HelpSupportBlockSelect<T extends boolean = true> {
  sectionTitle?: T;
  sectionSubtitle?: T;
  layout?: T;
  supportCards?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        iconColor?: T;
        buttonLabel?: T;
        buttonUrl?: T;
        id?: T;
      };
  video?:
    | T
    | {
        enabled?: T;
        title?: T;
        videoUrl?: T;
        poster?: T;
        uploadedVideo?: T;
      };
  backgroundColor?: T;
  cardBgColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FlexibleRowBlock_select".
 */
export interface FlexibleRowBlockSelect<T extends boolean = true> {
  containerWidth?: T;
  rowBackground?: T;
  rowPadding?: T;
  gridGap?: T;
  alignItems?: T;
  columns?:
    | T
    | {
        width?: T;
        columnStyle?: T;
        backgroundColor?: T;
        textColor?: T;
        columnPadding?: T;
        alignment?: T;
        image?: T;
        imagePosition?: T;
        imageShape?: T;
        title?: T;
        content?: T;
        ctaLabel?: T;
        ctaLink?: T;
        blocks?:
          | T
          | {
              colRichText?:
                | T
                | {
                    content?: T;
                    id?: T;
                    blockName?: T;
                  };
              colCard?:
                | T
                | {
                    image?: T;
                    title?: T;
                    description?: T;
                    ctaLabel?: T;
                    ctaLink?: T;
                    cardStyle?: T;
                    id?: T;
                    blockName?: T;
                  };
              colImage?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    aspectRatio?: T;
                    id?: T;
                    blockName?: T;
                  };
              colCta?:
                | T
                | {
                    label?: T;
                    link?: T;
                    style?: T;
                    id?: T;
                    blockName?: T;
                  };
              colEmbed?:
                | T
                | {
                    videoUrl?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedCardsBlock_select".
 */
export interface FeaturedCardsBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  columns?: T;
  cardStyle?: T;
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        image?: T;
        tag?: T;
        linkLabel?: T;
        link?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        gallery?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  tag?: T;
  excerpt?: T;
  slug?: T;
  content?: T;
  externalLink?: T;
  publishedAt?: T;
  featured?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  image?: T;
  caption?: T;
  event?: T;
  album?: T;
  date?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  youtubeUrl?: T;
  eventDate?: T;
  organizer?: T;
  description?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  image?: T;
  link?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committee_select".
 */
export interface CommitteeSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  designation?: T;
  photo?: T;
  bio?: T;
  type?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobApplications_select".
 */
export interface JobApplicationsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  resume?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  name?: T;
  membershipId?: T;
  photo?: T;
  designation?: T;
  university?: T;
  joinDate?: T;
  email?: T;
  phone?: T;
  isPublic?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo: number | Media;
  /**
   * Optional compact logo for small screens. Falls back to main logo if not set.
   */
  logoMobile?: (number | null) | Media;
  /**
   * Header stays visible at the top of the screen while scrolling.
   */
  sticky: boolean;
  /**
   * Header overlaps the homepage hero and is transparent initially.
   */
  overlapHomepageHero?: boolean | null;
  /**
   * Show/hide the light-dark mode toggle in the header.
   */
  showThemeSelector?: boolean | null;
  /**
   * Optional thin bar above the header, e.g. for urgent notices (admit cards, deadlines).
   */
  announcementBar?: {
    enabled?: boolean | null;
    message?: string | null;
    /**
     * Optional URL to link the announcement to
     */
    link?: string | null;
    dismissible?: boolean | null;
  };
  /**
   * Top-level navigation items. Keep to 8 or fewer for a clean desktop layout.
   */
  nav?:
    | {
        label: string;
        link?: string | null;
        openInNewTab?: boolean | null;
        /**
         * Render this item as a filled CTA button instead of a plain link (e.g. "Apply Now").
         */
        highlight?: boolean | null;
        children?:
          | {
              label: string;
              link: string;
              openInNewTab?: boolean | null;
              /**
               * Optional one-line description shown under the label in the dropdown (mega-menu style).
               */
              description?: string | null;
              subChildren?:
                | {
                    label: string;
                    link: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Add page slugs/URLs here (e.g., /about) to prevent them from automatically appearing in the header navigation.
   */
  navSyncHiddenPageUrls?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  organizationName: string;
  socialLinks?: {
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    youtube?: string | null;
  };
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  copyright: string;
  /**
   * Show the visitor statistics block in the footer
   */
  showVisitorCounter?: boolean | null;
  showCalendar?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * Configure and reorder sections on the homepage. If left empty, all default sections will render in the standard sequence.
   */
  layout?:
    | (
        | {
            carouselHeight: 'short' | 'medium' | 'tall' | 'fullscreen';
            carouselLayout: 'fullWidth' | 'boxed';
            carouselImageOpacity: '100' | '90' | '80' | '70' | '60' | '50';
            carouselAutoplay?: boolean | null;
            carouselAutoplayInterval?: number | null;
            slides?:
              | {
                  /**
                   * Slide image. WARNING: To change this image, click the "X" button to clear the field, then select or upload a new one. DO NOT click the pencil "Edit" icon to replace the file inside the media drawer, as that will overwrite the shared media asset globally across all pages!
                   */
                  image: number | Media;
                  alt?: string | null;
                  /**
                   * Optional: clicking the slide goes here
                   */
                  link?: string | null;
                  imageAlignment?: ('center' | 'top' | 'bottom' | 'left' | 'right') | null;
                  overlayOpacity?: ('none' | 'light' | 'medium' | 'dark' | 'extraDark') | null;
                  textAlignment?: ('left' | 'center' | 'right') | null;
                  title?: string | null;
                  subtitle?: string | null;
                  buttonLabel?: string | null;
                  buttonLink?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'carousel';
          }
        | {
            heading: string;
            align: 'left' | 'center' | 'right';
            size: 'small' | 'medium' | 'large';
            /**
             * Select up to 4 service cards to display
             */
            services?: (number | Service)[] | null;
            bg: 'white' | 'slate' | 'cream';
            showUnderline: boolean;
            id?: string | null;
            blockName?: string | null;
            blockType: 'services';
          }
        | {
            heading: string;
            align: 'left' | 'center' | 'right';
            size: 'small' | 'medium' | 'large';
            newsSubheading?: string | null;
            limit: number;
            newsViewAllLink: string;
            newsViewAllLabel: string;
            bg: 'white' | 'slate' | 'cream';
            showUnderline: boolean;
            id?: string | null;
            blockName?: string | null;
            blockType: 'news';
          }
        | {
            heading: string;
            align: 'left' | 'center' | 'right';
            size: 'small' | 'medium' | 'large';
            limit: number;
            galleryViewAllLabel: string;
            bg: 'white' | 'slate' | 'cream';
            showUnderline: boolean;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading: string;
            align: 'left' | 'center' | 'right';
            size: 'small' | 'medium' | 'large';
            limit: number;
            bg: 'white' | 'slate' | 'cream';
            showUnderline: boolean;
            id?: string | null;
            blockName?: string | null;
            blockType: 'events';
          }
      )[]
    | null;
  carouselHeight: 'short' | 'medium' | 'tall' | 'fullscreen';
  carouselLayout: 'fullWidth' | 'boxed';
  carouselImageOpacity: '100' | '90' | '80' | '70' | '60' | '50';
  carouselAutoplay?: boolean | null;
  carouselAutoplayInterval?: number | null;
  carousel?:
    | {
        /**
         * Slide image. WARNING: To change this image, click the "X" button to clear the field, then select or upload a new one. DO NOT click the pencil "Edit" icon to replace the file inside the media drawer, as that will overwrite the shared media asset globally across all pages!
         */
        image: number | Media;
        alt?: string | null;
        /**
         * Optional: clicking the slide goes here
         */
        link?: string | null;
        imageAlignment?: ('center' | 'top' | 'bottom' | 'left' | 'right') | null;
        overlayOpacity?: ('none' | 'light' | 'medium' | 'dark' | 'extraDark') | null;
        textAlignment?: ('left' | 'center' | 'right') | null;
        title?: string | null;
        subtitle?: string | null;
        buttonLabel?: string | null;
        buttonLink?: string | null;
        id?: string | null;
      }[]
    | null;
  offersHeading: string;
  offersHeadingAlignment: 'left' | 'center' | 'right';
  offersHeadingSize: 'small' | 'medium' | 'large';
  /**
   * Select up to 4 service cards to display
   */
  services?: (number | Service)[] | null;
  newsHeading: string;
  newsHeadingAlignment: 'left' | 'center' | 'right';
  newsHeadingSize: 'small' | 'medium' | 'large';
  newsSubheading?: string | null;
  /**
   * How many notification items to show on the homepage
   */
  newsDisplayCount: number;
  newsViewAllLink: string;
  galleryHeading: string;
  galleryHeadingAlignment: 'left' | 'center' | 'right';
  galleryHeadingSize: 'small' | 'medium' | 'large';
  galleryDisplayCount: number;
  eventsHeading: string;
  eventsHeadingAlignment: 'left' | 'center' | 'right';
  eventsHeadingSize: 'small' | 'medium' | 'large';
  eventsDisplayCount: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  favicon?: (number | null) | Media;
  /**
   * Select which page should be the home page. This will be displayed when visitors go to the root URL (/).
   */
  homePage?: string | null;
  /**
   * Choose a website theme. Selecting a preset automatically updates the colors, typography, header, and block layouts.
   */
  themePreset?: ('mosai' | 'mosaiClassic' | 'learner') | null;
  headingFont?: ('Playfair Display' | 'Raleway' | 'Montserrat' | 'Inter' | 'Roboto' | 'Poppins') | null;
  bodyFont?: ('Inter' | 'Roboto' | 'Open Sans' | 'Poppins' | 'Lato') | null;
  themeColors?: {
    /**
     * Pick primary brand color
     */
    primaryColor?: string | null;
    /**
     * Pick secondary brand color
     */
    secondaryColor?: string | null;
    /**
     * Pick accent/highlight color
     */
    accentColor?: string | null;
    /**
     * Main page background color
     */
    backgroundColor?: string | null;
    /**
     * Card/surface background color
     */
    surfaceColor?: string | null;
    /**
     * Section muted background color
     */
    mutedBackgroundColor?: string | null;
    /**
     * Default body text color
     */
    textColor?: string | null;
  };
  socialLinks?:
    | {
        platform: 'facebook' | 'twitter' | 'instagram' | 'youtube' | 'linkedin';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  logoMobile?: T;
  sticky?: T;
  overlapHomepageHero?: T;
  showThemeSelector?: T;
  announcementBar?:
    | T
    | {
        enabled?: T;
        message?: T;
        link?: T;
        dismissible?: T;
      };
  nav?:
    | T
    | {
        label?: T;
        link?: T;
        openInNewTab?: T;
        highlight?: T;
        children?:
          | T
          | {
              label?: T;
              link?: T;
              openInNewTab?: T;
              description?: T;
              subChildren?:
                | T
                | {
                    label?: T;
                    link?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  navSyncHiddenPageUrls?:
    | T
    | {
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  organizationName?: T;
  socialLinks?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedin?: T;
        youtube?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  copyright?: T;
  showVisitorCounter?: T;
  showCalendar?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        carousel?:
          | T
          | {
              carouselHeight?: T;
              carouselLayout?: T;
              carouselImageOpacity?: T;
              carouselAutoplay?: T;
              carouselAutoplayInterval?: T;
              slides?:
                | T
                | {
                    image?: T;
                    alt?: T;
                    link?: T;
                    imageAlignment?: T;
                    overlayOpacity?: T;
                    textAlignment?: T;
                    title?: T;
                    subtitle?: T;
                    buttonLabel?: T;
                    buttonLink?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        services?:
          | T
          | {
              heading?: T;
              align?: T;
              size?: T;
              services?: T;
              bg?: T;
              showUnderline?: T;
              id?: T;
              blockName?: T;
            };
        news?:
          | T
          | {
              heading?: T;
              align?: T;
              size?: T;
              newsSubheading?: T;
              limit?: T;
              newsViewAllLink?: T;
              newsViewAllLabel?: T;
              bg?: T;
              showUnderline?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              align?: T;
              size?: T;
              limit?: T;
              galleryViewAllLabel?: T;
              bg?: T;
              showUnderline?: T;
              id?: T;
              blockName?: T;
            };
        events?:
          | T
          | {
              heading?: T;
              align?: T;
              size?: T;
              limit?: T;
              bg?: T;
              showUnderline?: T;
              id?: T;
              blockName?: T;
            };
      };
  carouselHeight?: T;
  carouselLayout?: T;
  carouselImageOpacity?: T;
  carouselAutoplay?: T;
  carouselAutoplayInterval?: T;
  carousel?:
    | T
    | {
        image?: T;
        alt?: T;
        link?: T;
        imageAlignment?: T;
        overlayOpacity?: T;
        textAlignment?: T;
        title?: T;
        subtitle?: T;
        buttonLabel?: T;
        buttonLink?: T;
        id?: T;
      };
  offersHeading?: T;
  offersHeadingAlignment?: T;
  offersHeadingSize?: T;
  services?: T;
  newsHeading?: T;
  newsHeadingAlignment?: T;
  newsHeadingSize?: T;
  newsSubheading?: T;
  newsDisplayCount?: T;
  newsViewAllLink?: T;
  galleryHeading?: T;
  galleryHeadingAlignment?: T;
  galleryHeadingSize?: T;
  galleryDisplayCount?: T;
  eventsHeading?: T;
  eventsHeadingAlignment?: T;
  eventsHeadingSize?: T;
  eventsDisplayCount?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  favicon?: T;
  homePage?: T;
  themePreset?: T;
  headingFont?: T;
  bodyFont?: T;
  themeColors?:
    | T
    | {
        primaryColor?: T;
        secondaryColor?: T;
        accentColor?: T;
        backgroundColor?: T;
        surfaceColor?: T;
        mutedBackgroundColor?: T;
        textColor?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}